### PR TITLE
Implement static sidebars

### PR DESCRIPTION
**Pull request by jlvandenhout**
# Description of change

This adds the possibility to add static sidebars to sections. This PR only implements the logic, so the configuration is quite cumbersome, but we will have to fix that later. The sidebar is now split into 4 "areas": `before`, `switcher`, `main`, and `after`. `before` and `after` are optional static sidebars, `main` will display the sidebar of the current doc, unless it is already in `before` or `after`. To configure before and/or after, currently you have to:

1. Make the sidebar of the doc explicitly global by adding the sidebar ID (found in the associated `sidebars.ts` file) to the list in the `globalSidebars` option of the associated docs plugin. i.e.:

```js
  {
      id: 'build',
      globalSidebars: ['build'], // This ID comes from 'docs/build/getting-started/sidebars.ts'
      path: path.resolve(__dirname, 'docs/build/getting-started'),
      sidebarPath: path.resolve(
        __dirname,
        'docs/build/getting-started/sidebars.ts',
      ),
      routeBasePath: 'build',
    },
```
2. Configure the docs plugin ID and sidebar ID in the section where you want to add the static sidebar:

```js
    {
      before: {
        docId: 'build',
        sidebarId: 'build',
      },
      subsections: [
        {
          label: 'Layer 1',
          description: 'Build applications on our feeless multi-asset L1 DAG.',
          id: 'build-layer-1',
        },
        {
          label: 'Layer 2',
          description: 'Build dApps with ISC, our L2 smart contracts platform.',
          id: 'build-layer-2',
        },
      ],
    },
```

Obviously there are ways to make this configuration way easier and less error prone, but that's for another PR.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jlvandenhout** [comment]
@Dr-Electron @lucas-tortora could you check if this is clear to you, and indicate if we should already configure it like we would like it, or if you like to do that in a different PR?

**Comment by Dr-Electron** [comment]
I'm wondering which approach is better.
This one ore what the PaloAlto team is [doing](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/307690da340cb4890b9f68e32c01ed0a01a3c576/demo/sidebars.js#L105-L110)

If we are not fixing the config, their way seems to be the less complicated one without really changing anything 🤔

**Comment by Dr-Electron** [comment]
Also I have no idea why your workflow request was skipped 😅

**Comment by jlvandenhout** [comment]
> I'm wondering which approach is better.
> This one ore what the PaloAlto team is [doing](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/307690da340cb4890b9f68e32c01ed0a01a3c576/demo/sidebars.js#L105-L110)
> 
> If we are not fixing the config, their way seems to be the less complicated one without really changing anything 🤔 

We can't do that. We are not just adding a switcher, we are manipulating the complete sidebar structure. For example it wouldn't make sense to render the "default" sidebar of a doc, if it is already a static sidebar for that section. Doing it the palo alto doesn't really seem an option to me.

**Comment by jlvandenhout** [comment]
> Also I have no idea why your workflow request was skipped 😅 

It wasn't, it just failed for some reason: https://github.com/iotaledger/iota-wiki/actions/runs/5761614871/job/15619784889#step:11:6

**Comment by Dr-Electron** [comment]
> We can't do that. We are not just adding a switcher, we are manipulating the complete sidebar structure. For example it wouldn't make sense to render the "default" sidebar of a doc, if it is already a static sidebar for that section. Doing it the Palo Alto way doesn't really seem an option to me.

They also change the sidebar.
Not sure what you mean with the second part of the reply 😅. Why wouldn't it make sense?

**Comment by Dr-Electron** [comment]
Preview: https://iota-wiki-e5v405cdl-iota1.vercel.app/

**Comment by Dr-Electron** [comment]
As discussed my solution won't work with the current multi plugin setup. We might revisit later. But for now we need to go with this solution

**Review by Dr-Electron — APPROVED** [review]
Looks good to me

**Pull request merged**
