### PR TITLE
Add version redirects to current version

### LINKED ISSUE #1086: Allow "deep" links to main version of versioned project
**Is your feature request related to a problem? Please describe.**

Currently we link to the stable release of for example identity with /identity.rs/...
But would be nice if /identity.rs/v0.6 would link to the same version.

A possible solution could be to use the[ client redirect plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects/). Not sure if this would be dependent on #1083.

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

This PR adds version redirects so that the current version is not only accessible from `/<project>/**` but also from `/<project>/<current-version>/**`

## Links to any relevant issues

Fixes #1086.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Dr-Electron** [comment]
So now you could either use:
https://iota-wiki-98xis31i6-iota1.vercel.app/identity.rs/introduction/
or
https://iota-wiki-98xis31i6-iota1.vercel.app/identity.rs/0.6/introduction/

which doesn't work in the current wiki:
http://wiki.iota.org/identity.rs/0.6/introduction/

**Comment by jlvandenhout** [comment]
We can do this later but: have you considered doing it the other way around? So just give every version a `/<project>/<version>` path and then point `/<project>` to a configured default version?

**Comment by Dr-Electron** [comment]
> We can do this later but: have you considered doing it the other way around? So just give every version a `/<project>/<version>` path and then point `/<project>` to a configured default version?

I thought about it. But never went through the idea properly 🤔 
Could make more sense. Let's revisit after we have versioning where we want it to be, where we have redirects for Shimmer and the first verion in the config for every network is the main version

**Review by jlvandenhout — APPROVED** [review]

**Comment by eike-hass** [comment]
> Member

The result, or more accurately the deep-linking capabilities would be the same then, right?

**Comment by Dr-Electron** [comment]
> > I thought about it. But never went through the idea properly 🤔
> > Could make more sense. Let's revisit after we have versioning where we want it to be, where we have redirects for Shimmer and the first verion in the config for every network is the main version
> 
> The result, or more accurately the deep-linking capabilities would be the same then, right?

Yes

**Pull request merged**
