### PR TITLE
Fix OpenAPI

### LINKED ISSUE #1095: OpenAPI broken
**Describe the bug**

There are two things broken in the current OpenAPI sections of the wiki.
1) On [add-a-given-peer-to-the-node](https://wiki.iota.org/develop/nodes/rest-api/add-a-given-peer-to-the-node/) for example I get the common error: `Docusaurus error: Duplicate values "default" found in <Tabs>. Every value needs to be unique.`
2) On [shimmer/iota-core-rest-api](https://wiki.iota.org/shimmer/develop/nodes/core-rest-api/iota-core-rest-api/)I can't navigate to the next site

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

Fixed the openAPI issues. We are using our own fork for the openAPI plugin until https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/611 gets merged. If it doesn't get merged we need to find another solution.

## Links to any relevant issues

Fixes #1095 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Documentation Fix

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jlvandenhout** [comment]
@Dr-Electron I rebased my fork on beta.3 and updated the theme package to use their beta.3 release, can you check if this works for you now?

**Review by jlvandenhout — DISMISSED** [review]

**Comment by Dr-Electron** [comment]
Closed in favour of https://github.com/iotaledger/iota-wiki/pull/1044/commits/51e7a869fb6219663e4e2ee94b216e41d9ef6128

**Pull request closed without merging**
