### PR TITLE
The merge - move docs to wiki

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

- [x] Moved IOTA docs to the wiki
- [x] Moved Shimmer docs to the wiki
- [x] Moved Next docs to the wiki

## Links to any relevant issues

fixes https://github.com/iotaledger/guild-devx/issues/81

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [ ] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by jlvandenhout — APPROVED** [review]

**Comment by Dr-Electron** [comment]
What about TIPs? Do we just keep importing them from time to time?
I think we should still import them the old way 🤔. They are not really complex and don't need any special stuff from the cli, so I guess it should be fine maintaining them that way. Wdyt?

**Review by Dr-Electron — CHANGES_REQUESTED** [review]
Problems I found:

# IOTA

## iota.rs
- [x] `/examples/running_examples/` empty tabs, as `/libraries/*language*/examples/_running_examples.mdx` are empty 98fc7dcf03ae4b4f03b6b9d7bce9766a5a52c805
- [x] `/libraries/java/api_reference/` empty page
- [x] `/libraries/rust/api_reference/` empty page
- [x] `/libraries/wasm/api_reference/` empty page

## wallet.rs
- [x] `/overview/` maybe let's fix this image one last time? :laughing: 98fc7dcf03ae4b4f03b6b9d7bce9766a5a52c805
- [x] `/explanations/nutshell/` same

## Identity
- [x] Missing nodejs examples. We should copy them from replit I guess. 5359d14d318dccbe35e6a33ce41807c7f7761f93

## Stronghold
- [x] Most pages content is missing 0cc4bbe74dd01081834f69c736d7cf4e9bcdbf74, 87b99acb2026b9c14909a2d9c98ee77e5241d1fe

## TIPs
- [x] As I said above, I would import those. Also why did you remove my sidebar code? :sadness: It adds the TIP number and flattens the hierarchy which is quite convinient imo.

# Shimmer
## Chronicle
- [x] Wrong docs 4948c3323ec65278f7a582900bc54cf7518d97dd

## Identity
- [x] `/concepts/decentralized_identifiers/resolve/#resolving-multiple-did-methods` missing examples 243e6acdeb5f62f3920b9b3f456283a8a8d7e243

## iota.js
- [x] `/how_tos/browser/#example-code` missinc example

# Common
## docusaurus.config.js 
- [x] Newlines which aren't needed
- [x] Would be nice to sort plugins by docs/plugins/tutorials in that order
- [x] Fix edit urls

**Comment by lucas-tortora** [comment]
@Dr-Electron , two things about the edit URLs:

**Comment by Dr-Electron** [comment]
> @Dr-Electron , two things about the edit URLs:
> 
> 1. Did someone swizzle the component or is it just acting out for some reason?  I can't get it to work properly without having to do stuff like: `          'https://github.com/iotaledger/iota-wiki/edit/the-merge-moveRemainingDocsToWiki/shimmer/shimmer/external/stronghold.rs/docs',`
> 2. We'll need to come back to this to update the branch once we sort out any issues and merge

Yeah the component is swizzled. We can fix it in another PR. I think it gets triggered because the docs are in the external folder (which we will change anyway I guess, so it should resolve itself)

**Review by Dr-Electron — CHANGES_REQUESTED** [review]
Those are still empty?
- [x]  /libraries/java/api_reference/ empty page
- [x]  /libraries/rust/api_reference/ empty page
- [x]  /libraries/wasm/api_reference/ empty page

And this is also not yet fixed:
- [ ]  /explanations/nutshell/ same

Also: Why do we need the api references for chronicle?

**Review by Dr-Electron — APPROVED** [review]
For the sake of it getting rid of it, I will merge it now. But this things still need to be done:
iota.rs
- [ ]  /libraries/java/api_reference/ empty page
- [ ]  /libraries/rust/api_reference/ empty page
- [x]  /libraries/wasm/api_reference/ empty page

wallet.rs
- [ ]  /explanations/nutshell/ same

chronicle
- [ ] Remove API specs

**Pull request merged**
