### PR TITLE
Update reference script

### LINKED ISSUE #1183: Add action to pull auto generated docs from server
**Is your feature request related to a problem? Please describe.**

Currently we pull the SDK docs to build the API references. This is time consuming and not efficient as we pull on every build although the API references might not have changed. This will also happen for other API references which are not autogenerated yet, like for Identity or for the autogenerated config docs from app.go.

**Describe the solution you'd like**

The idea like it is described here https://github.com/iotaledger/devops/issues/377 would be to upload those files from the repos to a server so that the wiki can download them on build

**Describe alternatives you've considered**

It would also be possible to upload this files to the Releases, but that isn't really a nice solution imo

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

I changed the sdk references script to just download the references as we are now creating them in the [SDK](https://github.com/iotaledger/iota-sdk/pull/1412)

## Links to any relevant issues

Fixes #1183.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Dr-Electron** [comment]
I will wait with this until https://github.com/iotaledger/iota-sdk/pull/1412 gets merged. Just to be sure they don't want anything changed (I don't think so, but you never know)

**Review by jlvandenhout — APPROVED** [review]
I really like this!

**Comment by lucas-tortora** [comment]
https://iota-wiki-8k59unmzh-iota1.vercel.app/

**Comment by Dr-Electron** [comment]
PR in the SDK got merged. Let's gooo ;)

**Pull request merged**
