### PR TITLE
Swizzle version banner

### LINKED ISSUE #1087: Swizzle Versioning banners
**Is your feature request related to a problem? Please describe.**

We should swizzle(?) the versioning banner to mark our docs as for example deprecated.
But maybe it would be easier to create a new component and wrap the docs content. That way in the plugin we could specify a custom text even.

### PR DESCRIPTION
**Pull request by jlvandenhout**
# Description of change

This changes the version banner to show a deprecation caution when 'unmaintained' is used as banner value for that version. It shows a link to the latest version, if available and not the same as the deprecated version.

## Links to any relevant issues

fixes #1087 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes

### CODE REVIEW

**Comment by jlvandenhout** [comment]
@Dr-Electron would this suffice for now?

**Comment by Dr-Electron** [comment]
Maybe that's already too complicated, but what if we just allow custom banners?
That way every project could add custom banners with content like: `unreleased`, `unmaintained` and more.

**Comment by eike-hass** [comment]
Awesome stuff 💪 I think ideally the the banners would be flexible what content/text they display so they can be used many (including not anticipated) use-cases,

**Comment by jlvandenhout** [comment]
> Maybe that's already too complicated, but what if we just allow custom banners? That way every project could add custom banners with content like: `unreleased`, `unmaintained` and more.
> I think ideally the the banners would be flexible what content/text they display so they can be used many (including not anticipated) use-cases

Yes, that would be ideal of course, but "just allow custom banners" is not really how Docusaurus thought of it, they hardcoded their banner options and validate the config as such too. So "not too complicated" and "flexible banners" would be on the opposite sides of the spectrum. Let me think this through for a bit.

**Comment by Dr-Electron** [comment]
Maybe we should ask them to change it ;)

**Comment by jlvandenhout** [comment]
Closing in favor of #1103

**Pull request closed without merging**
