### PR TITLE
replace private tangle with Sandbox

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* replace private tangle with Sandbox

## Type of change

- Documentation Fix

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by eike-hass** [comment]
We have to integrate the sandbox in our CI and local workflow first, before we can accept this PR

**Comment by eike-hass** [comment]
The move to sandbox requires some changes to the examples and readmes (https://github.com/iotaledger/identity.rs/pull/1290).

I think we should merge these wiki changes with the next version of identity to keep it consistent. This would only make it consistent for the upcoming version (1.1) though. To also make it consistent with the current 1.0 version we would need a hotfix with the same changes. 
Will the private tangle be removed from hornet anytime soon? Otherwise we could leave 1.0 as is.

**Comment by lucas-tortora** [comment]
> The move to sandbox requires some changes to the examples and readmes ([iotaledger/identity.rs#1290](https://github.com/iotaledger/identity.rs/pull/1290)).
> 
> I think we should merge these wiki changes with the next version of identity to keep it consistent. This would only make it consistent for the upcoming version (1.1) though. To also make it consistent with the current 1.0 version we would need a hotfix with the same changes. Will the private tangle be removed from hornet anytime soon? Otherwise we prefer to leave 1.0 as is and use sandbox from 1.1 onwards.

I don't think it'll be removed, we're just moving away from the term for the most part. We can probably leave it as is in 1.0 and use the sandbox as of 1.1. @Dr-Electron, any thoughts on this?

**Comment by eike-hass** [comment]
> > The move to sandbox requires some changes to the examples and readmes ([iotaledger/identity.rs#1290](https://github.com/iotaledger/identity.rs/pull/1290)).
> > I think we should merge these wiki changes with the next version of identity to keep it consistent. This would only make it consistent for the upcoming version (1.1) though. To also make it consistent with the current 1.0 version we would need a hotfix with the same changes. Will the private tangle be removed from hornet anytime soon? Otherwise we prefer to leave 1.0 as is and use sandbox from 1.1 onwards.
> 
> I don't think it'll be removed, we're just moving away from the term for the most part. We can probably leave it as is in 1.0 and use the sandbox as of 1.1. @Dr-Electron, any thoughts on this?

That would be ideal, with next version after that (1.2) we would likely rotate out 1.0 and then it would become a non issue

**Comment by eike-hass** [comment]
Adopted changes for Identity v1.1 [here](https://github.com/iotaledger/iota-wiki/pull/1414/commits/6850badd0240ca0a331d07efd453236547e41b23)

**Comment by Dr-Electron** [comment]
There is a PR that renames the private tangle folder in hornet, but other then that currently no one cares about hornet so nothing will change in the near future 😆. So you should be fine continue using it

**Comment by Dr-Electron** [comment]
Can you resolve the conflicts?

**Review by Dr-Electron — APPROVED** [review]

**Pull request merged**
